// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCep3Vt3gK0cFFr6949u6FATuzMXCbf2KE',
    appId: '1:409470543055:web:e94442eb3ba6591ae3c3ba',
    messagingSenderId: '409470543055',
    projectId: 'fooddeliveryapp-aff4e',
    authDomain: 'fooddeliveryapp-aff4e.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-aff4e.appspot.com',
    measurementId: 'G-2VY27DYZ1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJcrBnNn28O5AgpldeS9gb1s4xbICQMbs',
    appId: '1:409470543055:android:b560994ba431e23ce3c3ba',
    messagingSenderId: '409470543055',
    projectId: 'fooddeliveryapp-aff4e',
    storageBucket: 'fooddeliveryapp-aff4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgicHU8AvrIe8zy0-9tHqakdiSSaif9M',
    appId: '1:409470543055:ios:a7a654543cc37f31e3c3ba',
    messagingSenderId: '409470543055',
    projectId: 'fooddeliveryapp-aff4e',
    storageBucket: 'fooddeliveryapp-aff4e.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNgicHU8AvrIe8zy0-9tHqakdiSSaif9M',
    appId: '1:409470543055:ios:a7a654543cc37f31e3c3ba',
    messagingSenderId: '409470543055',
    projectId: 'fooddeliveryapp-aff4e',
    storageBucket: 'fooddeliveryapp-aff4e.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCep3Vt3gK0cFFr6949u6FATuzMXCbf2KE',
    appId: '1:409470543055:web:feda342a8197ace4e3c3ba',
    messagingSenderId: '409470543055',
    projectId: 'fooddeliveryapp-aff4e',
    authDomain: 'fooddeliveryapp-aff4e.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-aff4e.appspot.com',
    measurementId: 'G-QGDK1RTXHB',
  );
}
